wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717590082.0
    t:
      1:
      - 1
      - 15
      - 41
      - 55
      - 105
      2:
      - 1
      - 15
      - 41
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.10.14
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
